version: "3.7"
services:
  p-build:
      build: .
      container_name: "lang-frontend"
      volumes:
          - type: volume
            source: out
            target: /www/app/lang-frontend
      networks:
          - mynet

volumes:
    out:
        external: true

networks:
    mynet:
        external: true
